# ======================
# COMMON CONFIGURATION #
# ======================
x-common-env: &common-env
  KEY : "totally-secret-key"
  ALGORITHM : "HS256"
  ACCESS_TOKEN_EXPIRATION_TIME : 60



# ==========
# SERVICES #
# ==========
services:

  # =============
  # FRONTEND UI #
  # =============
  app:
    build: ./front
    container_name: app_frontend
    ports:
      - "5000:8000"
    volumes:
      - .:/front/app
      - ./web:/app/web
    restart: always


  # =============
  # API GATEWAY #
  # =============
  gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - model_service
    restart: always


  # ======================
  # INFRASTRUCTURE KAFKA #
  # ======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      retries: 20


  # ============================
  # BASE DE DONNÉES - POSTGRES #
  # ============================
  postgres_users:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - pg_users_data:/var/lib/postgresql/data

  postgres_logs:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs_db
    ports:
      - "5434:5432"
    volumes:
      - pg_logs_data:/var/lib/postgresql/data

  postgres_models:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: models_db
    ports:
      - "5435:5432"
    volumes:
      - pg_models_data:/var/lib/postgresql/data


  # =====================
  # SERVICE UTILISATEUR #
  # =====================
  user_service:
    build: ./user-service
    depends_on:
      - kafka
      - postgres_users
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgres://user:password@postgres_users:5432/users_db
    volumes:
      - ./db_user:/app/db_user



  # ================
  # SERVICE MODÈLE #
  # ================
  model_service:
    build: ./model-service
    depends_on:
      - kafka
      - postgres_models
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./model-service:/app
      - ./training-program/kafka_utils:/app/kafka_utils



  # ================
  # CONSUMER KAFKA #
  # ================
  log_service:
    build: ./log-service
    command: python consumer.py
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DATABASE_URL: postgres://user:password@postgres_logs:5432/logs_db
    volumes:
      - ./db_logs:/app/db_logs
    restart: always



  # ================
  # PRODUCER KAFKA #
  # ================
  user_producer:
    build: ./user-service
    command: python producer.py
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./db_user:/app/db_user
    restart: always


  # ========================
  # ENTRAÎNEMENT - PYTORCH #
  # ========================
  training_pytorch:
    build: ./training-program
    container_name: training_pytorch
    command : python pytorch_training.py
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./training-program:/app
    restart: always


  # ===========================
  # ENTRAÎNEMENT - TENSORFLOW #
  # ===========================
  training_tensorflow:
    build: ./training-program
    container_name: training_tensorflow
    command: python tensorflow_training.py
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./training-program:/app
    restart: always


# =========
# VOLUMES #
# =========
volumes:
  pg_users_data:
  pg_logs_data:
  pg_models_data: