# Architecture de différents modèles de deep learning pour la reconnaissance d'images
# Librairies utilisées: pytorch et tensorflow

dataset:
  name: fashion_mnist_classification
  input_shape: [1, 28, 28]
  num_classes: 10

training:
    batch_size: 64
    epochs: 3
    learning_rate: 0.001
    validation_split: 0.2
    shuffle: true
    random_seed: 42
    optimizer:
        type: Adam
        learning_rate: 0.001

models:
  mlp_v1:
    architecture:
      type: MLP
      layers:
        - type: Flatten
        - type: Dense
          units: 128
          activation: relu
        - type: dense
          units: 10
          activation: softmax

